# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "eks-stable-diffusion-terraform-state"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "dev/terraform/call_center/terraform.tfstate"
    region         = "us-west-2"
  }
}
